root: true

parserOptions:
  sourceType: module
  ecmaVersion: 2020
  ecmaFeatures:
    jsx: true

plugins: ['react']

env:
  es6: true
  browser: true
  commonjs: true

extends:
  ['htmlacademy/es6', 'plugin:react/recommended']

settings:
  react:
    version: '17'
